services:
  server:
    container_name: work-room-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./server:/app
      - /build/node_modules
    networks:
      - Work-Room
    ports:
      - "3000:3000"

  client:
    container_name: work-room-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./client:/app
      - /build/node_modules
    networks:
      - Work-Room
    ports:
      - "5173:5173"
    depends_on:
      - server

networks:
  Work-Room:
    driver: bridge
